In [63]:
import pandas as pd
import re
import numpy as np

# Import raw data

In [64]:
df = pd.read_csv('JHU/proteinGroups.txt', delimiter='\t')

/tmp/ipykernel_2359/2500162998.py:1: DtypeWarning: Columns (504,505) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('JHU/proteinGroups.txt', delimiter='\t')

In [65]:
reporter_columns = list()
rename = list()
for j in range(1,14):
    if j < 10:
        reporter_columns += ['Reporter intensity corrected {} 0{}CPTAC'.format(i, j) for i in range(1, 11)]
        rename += ['0{}CPTAC_{}'.format(j, i) for i in range(1, 11)]
    else :
        reporter_columns += ['Reporter intensity corrected {} {}CPTAC'.format(i, j) for i in range(1, 11)]
        rename += ['{}CPTAC_{}'.format(j, i) for i in range(1, 11)]


export_df = df[reporter_columns]
export_df = export_df.rename(columns=dict(zip(reporter_columns, rename)))
export_df

,01CPTAC_1,01CPTAC_2,01CPTAC_3,01CPTAC_4,01CPTAC_5,01CPTAC_6,01CPTAC_7,01CPTAC_8,01CPTAC_9,01CPTAC_10,...,13CPTAC_1,13CPTAC_2,13CPTAC_3,13CPTAC_4,13CPTAC_5,13CPTAC_6,13CPTAC_7,13CPTAC_8,13CPTAC_9,13CPTAC_10
0,27677.0,15171.00,25346.0,29941.0,26480.0,14785.00,13287.00,17247.00,21893.0,37050.0,...,23163.0,30472.0,30621.0,28317.0,29076.0,41663.0,42953.0,25805.0,16976.0,11920.0
1,283950.0,77176.00,117790.0,79303.0,116910.0,73513.00,65731.00,119950.00,85775.0,124780.0,...,188660.0,86061.0,188230.0,77881.0,88370.0,90284.0,48588.0,56904.0,56117.0,103170.0
2,351900.0,119620.00,189520.0,381480.0,310500.0,161670.00,111780.00,199510.00,397900.0,401440.0,...,938670.0,965680.0,1144400.0,519050.0,919550.0,953600.0,768550.0,699920.0,344990.0,350620.0
3,19754.0,9131.10,11925.0,9875.1,9345.2,10534.00,4209.20,7530.60,9968.6,10497.0,...,24772.0,12504.0,42642.0,11287.0,21209.0,20460.0,16794.0,14216.0,8168.9,12857.0
4,52983.0,23801.00,26028.0,33492.0,28467.0,33439.00,36217.00,27205.00,23985.0,31448.0,...,395430.0,228100.0,375570.0,483270.0,353710.0,229670.0,229910.0,280530.0,445250.0,393030.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10559,3616.3,1074.50,3897.6,1685.7,2979.3,822.61,1543.40,1148.70,2410.2,8745.8,...,30350.0,59018.0,24143.0,30960.0,21549.0,20916.0,46540.0,22597.0,33166.0,14056.0
10560,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10561,128770.0,41545.00,41458.0,34164.0,31163.0,26298.00,21799.00,41123.00,19550.0,36768.0,...,82656.0,20248.0,121300.0,113970.0,56339.0,21804.0,15434.0,32374.0,23468.0,31032.0
10562,2910.1,2052.60,2520.5,2127.5,2452.0,2707.00,1595.30,2640.70,2857.1,3117.4,...,8019.4,3591.6,4183.2,6088.1,3652.6,4151.8,2870.1,3201.2,2250.6,2286.7
10563,1505.8,583.67,1997.2,1210.2,1468.0,604.19,824.54,700.27,1603.6,1897.6,...,9616.3,8763.2,8477.7,12065.0,11656.0,7317.2,9483.3,11922.0,7590.8,7725.8

# Normalization

In [66]:
#normalisation skipped for now discussion in meeting
export_df = export_df.apply(lambda x : np.log1p(x))
mean_features = export_df.mean(axis=1)
std_features = export_df.std(axis=1)

export_df_normalized = export_df.apply(lambda x : x - mean_features)
export_df_normalized = export_df_normalized.apply(lambda x : x/std_features)

#export_df_normalized.fillna(0.0)

# def normalized_by_CPTAC(sample_data):
#     _, columns = sample_data.shape
#     sample_data_group_normalized = list()
#     for i in range(0, columns, 10):
#         cptac_samples = sample_data.iloc[:, i: i+10]
#         sample_data_group_normalized.append((cptac_samples - cptac_samples.mean(axis=1))/cptac_samples.std(axis=1).fillna(0.0))
    
#     return pd.concat(sample_data_group_normalized, axis=0)

#export_df_group_normalized = normalized_by_CPTAC(export_df)

# Metadata

In [67]:
export_df_normalized

,01CPTAC_1,01CPTAC_2,01CPTAC_3,01CPTAC_4,01CPTAC_5,01CPTAC_6,01CPTAC_7,01CPTAC_8,01CPTAC_9,01CPTAC_10,...,13CPTAC_1,13CPTAC_2,13CPTAC_3,13CPTAC_4,13CPTAC_5,13CPTAC_6,13CPTAC_7,13CPTAC_8,13CPTAC_9,13CPTAC_10
0,0.935603,-0.086369,0.786048,1.069258,0.860449,-0.130177,-0.311762,0.131637,0.537098,1.431399,...,0.632951,1.099141,1.107433,0.974463,1.019426,1.630872,1.682706,0.816556,0.104716,-0.496306
1,1.551572,-0.197678,0.370067,-0.161171,0.359997,-0.262972,-0.413216,0.394467,-0.055829,0.447476,...,1.002573,-0.051359,0.999509,-0.185467,-0.015808,0.012965,-0.818991,-0.606850,-0.625550,0.192115
2,-0.473628,-2.233779,-1.483126,-0.341969,-0.677800,-1.742391,-2.344356,-1.399330,-0.273224,-0.258776,...,1.126813,1.173089,1.450080,0.160360,1.093243,1.152555,0.800632,0.648046,-0.505979,-0.479573
3,0.668724,0.438768,0.518318,0.462110,0.445675,0.481358,0.208015,0.381343,0.464918,0.480309,...,0.736181,0.532446,0.898038,0.501932,0.689904,0.679189,0.620348,0.570685,0.405587,0.540742
4,-1.199512,-2.270995,-2.151234,-1.813642,-2.031302,-1.815763,-1.708907,-2.092016,-2.260684,-1.897957,...,1.491828,0.755135,1.422832,1.760430,1.342536,0.764320,0.765718,1.032165,1.650714,1.483676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10559,-0.017790,-0.469880,0.010123,-0.302160,-0.089988,-0.569339,-0.335011,-0.445014,-0.168967,0.311308,...,0.775027,1.022898,0.689751,0.782444,0.647387,0.636275,0.934367,0.665086,0.808097,0.488140
10560,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,...,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322
10561,1.244693,-0.185421,-0.188071,-0.432699,-0.548928,-0.763505,-1.000697,-0.198328,-1.138348,-0.339839,...,0.684224,-1.094001,1.169143,1.090344,0.199661,-1.000407,-1.437192,-0.500733,-0.907436,-0.554253
10562,0.264142,0.152504,0.218174,0.163965,0.209363,0.241004,0.071909,0.233074,0.258264,0.286151,...,0.588388,0.331440,0.380212,0.500248,0.336827,0.377802,0.259716,0.294635,0.181953,0.187042
10563,-0.476325,-1.209986,-0.257583,-0.645560,-0.496014,-1.183254,-0.942629,-1.069061,-0.427590,-0.297207,...,0.960141,0.888155,0.862490,1.135926,1.109201,0.748420,0.949349,1.126686,0.776864,0.790524

In [68]:
meta_df = pd.read_csv('JHU/PCD_study_experimental_CPTAC_info.tsv', delimiter='\t')
meta_df = meta_df.drop(columns=['Run Metadata ID', 'Number of Fractions', 'Protocol'])

In [69]:
meta_df

,tmt_126,tmt_127n,tmt_127c,tmt_128n,tmt_128c,tmt_129n,tmt_129c,tmt_130n,tmt_130c,tmt_131
0,"pooled sample, Not Reported","15OV001, Primary Tumor","11OV009, Primary Tumor","17OV014, Primary Tumor","04OV048, Primary Tumor","02OV001, Primary Tumor","15OV001, Solid Tissue Normal","04OV008, Primary Tumor","17OV039, Primary Tumor","04OV044, Primary Tumor"
1,"pooled sample, Not Reported","01OV039, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported","01OV008, Solid Tissue Normal","01OV041, Primary Tumor","18OV001, Primary Tumor","04OV040, Primary Tumor","04OV045, Primary Tumor","01OV041, Solid Tissue Normal","04OV050, Primary Tumor"
2,"pooled sample, Not Reported","02OV008, Primary Tumor","04OV005, Primary Tumor","17OV004, Solid Tissue Normal","17OV015, Primary Tumor","04OV063, Primary Tumor","01OV017, Solid Tissue Normal","Ovarian Tumor Sample 5776, Not Reported","01OV017, Primary Tumor","04OV011, Primary Tumor"
3,"pooled sample, Not Reported","04OV012, Primary Tumor","01OV018, Primary Tumor","04OV028, Primary Tumor","14OV011, Primary Tumor","02OV035, Primary Tumor","04OV021, Primary Tumor","11OV002, Solid Tissue Normal","02OV042, Primary Tumor","14OV011, Solid Tissue Normal"
4,"pooled sample, Not Reported","01OV019, Primary Tumor","02OV022, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported","17OV005, Solid Tissue Normal","17OV034, Primary Tumor","01OV026, Primary Tumor","01OV026, Solid Tissue Normal","02OV032, Primary Tumor","26OV010, Primary Tumor"
5,"pooled sample, Not Reported","01OV023, Solid Tissue Normal","04OV023, Primary Tumor","04OV041, Primary Tumor","04OV027, Primary Tumor","01OV023, Primary Tumor","04OV055, Primary Tumor","04OV037, Primary Tumor","04OV031, Primary Tumor","01OV024, Solid Tissue Normal"
6,"pooled sample, Not Reported","22OV001, Solid Tissue Normal","17OV012, Primary Tumor","22OV001, Primary Tumor","04OV017, Primary Tumor","17OV036, Primary Tumor","17OV029, Primary Tumor","02OV045, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported","02OV040, Primary Tumor"
7,"pooled sample, Not Reported","02OV015, Primary Tumor","04OV051, Primary Tumor","04OV036, Primary Tumor","11OV010, Solid Tissue Normal","01OV007, Primary Tumor","01OV007, Solid Tissue Normal","04OV018, Primary Tumor","04OV049, Primary Tumor","17OV019, Primary Tumor"
8,"pooled sample, Not Reported","Ovarian Tumor Sample 5776, Not Reported","01OV030, Solid Tissue Normal","04OV013, Primary Tumor","02OV023, Primary Tumor","01OV030, Primary Tumor","17OV018, Primary Tumor","04OV039, Primary Tumor","14OV029, Solid Tissue Normal","04OV058, Primary Tumor"
9,"pooled sample, Not Reported","01OV046, Primary Tumor","01OV045, Solid Tissue Normal","01OV045, Primary Tumor","04OV033, Primary Tumor","26OV002, Primary Tumor","01OV010, Solid Tissue Normal","17OV025, Primary Tumor","17OV028, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported"
10,"pooled sample, Not Reported","04OV024, Primary Tumor","04OV054, Primary Tumor","04OV004, Primary Tumor","17OV002, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported","17OV002, Solid Tissue Normal","17OV011, Primary Tumor","04OV001, Primary Tumor","01OV049, Primary Tumor"
11,"pooled sample, Not Reported","04OV057, Primary Tumor","17OV013, Primary Tumor","26OV009, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported","01OV013, Solid Tissue Normal","17OV001, Solid Tissue Normal","17OV001, Primary Tumor","02OV005, Primary Tumor","13OV004, Primary Tumor"
12,"pooled sample, Not Reported","26OV008, Primary Tumor","Ovarian Tumor Sample 5776, Not Reported","01OV029, Primary Tumor","17OV030, Primary Tumor","17OV017, Primary Tumor","20OV005, Primary Tumor","04OV053, Primary Tumor","01OV029, Solid Tissue Normal","17OV003, Solid Tissue Normal"

In [70]:
def patient_string_processing(patient_string):
    sample, condition = patient_string.split(",")
    if re.search('^Ovarian.*', sample):
        return "Ovarian Tumor Sample"
    else:
        return condition
patient_conditions = meta_df.stack().tolist()
conditions = [patient_string_processing(patient) for patient in patient_conditions]
conditions

[' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 'Ovarian Tumor Sample',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Not Reported',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Not Reported',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Not Reported',
 'Ovarian Tumor Sample',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Solid Tissue Normal',
 ' Solid Tissue Normal',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Not Reported',
 ' Primary Tumor',
 'Ovarian Tumor Sample',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Primary Tumor',
 ' Solid Tissue Normal',
 ' Solid Tissue Normal']

# Export

In [71]:
condition_df = pd.DataFrame( dict(zip(rename, conditions)), index=['Conditions'])

export_df = pd.concat([export_df, condition_df], axis=0 )
export_df_normalized = pd.concat([export_df_normalized, condition_df], axis=0 )
#export_df_group_normalized = pd.concat([export_df_group_normalized, condition_df], axis=0 )

In [72]:
export_df.to_csv('real_dataset_raw.tsv', sep='\t')
export_df_normalized.to_csv('real_dataset_normalized.tsv', sep='\t')
#export_df_group_normalized.to_csv('real_dataset_normalized_by_cptac.tsv', sep='\t')

In [73]:
export_df

,01CPTAC_1,01CPTAC_2,01CPTAC_3,01CPTAC_4,01CPTAC_5,01CPTAC_6,01CPTAC_7,01CPTAC_8,01CPTAC_9,01CPTAC_10,...,13CPTAC_1,13CPTAC_2,13CPTAC_3,13CPTAC_4,13CPTAC_5,13CPTAC_6,13CPTAC_7,13CPTAC_8,13CPTAC_9,13CPTAC_10
0,10.228393,9.627207,10.140416,10.307017,10.184183,9.601436,9.494617,9.755451,9.993968,10.520051,...,10.050355,10.324596,10.329474,10.251253,10.277703,10.637393,10.667885,10.158362,9.739615,9.386057
1,12.556557,11.253857,11.676667,11.281044,11.669168,11.205231,11.093341,11.694839,11.359495,11.734315,...,12.147707,11.362823,12.145425,11.26295,11.389299,11.410727,10.791152,10.949138,10.935212,11.544143
2,12.771105,11.692084,12.152255,12.851816,12.645942,11.993319,11.624297,12.203625,12.893959,12.902816,...,13.75222,13.780589,13.950392,13.159757,13.731641,13.768001,13.552262,13.458723,12.751274,12.767461
3,9.891162,9.119551,9.386476,9.197873,9.142725,9.262458,8.345265,8.926863,9.207296,9.25894,...,10.11751,9.433884,10.660618,9.331495,9.962228,9.926276,9.728837,9.562194,9.008212,9.461721
4,10.877745,10.077525,10.166967,10.419092,10.256536,10.417508,10.497312,10.211193,10.085226,10.356122,...,12.887732,12.337544,12.836203,13.088333,12.776235,12.344403,12.345448,12.54444,13.006393,12.881644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10560,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10561,11.765791,10.634557,10.63246,10.438957,10.347019,10.177286,9.989665,10.624347,9.880782,10.51241,...,11.322455,9.915861,11.70603,11.643699,10.93916,9.989895,9.644393,10.385142,10.063436,10.342806
10562,7.976286,7.62735,7.832609,7.663173,7.805067,7.903966,7.375444,7.879178,7.957912,8.045075,...,8.989744,8.186631,8.339071,8.714256,8.203468,8.331538,7.962451,8.071593,7.719396,7.735302
10563,7.317743,6.371048,7.600002,7.099367,7.292337,6.405542,6.716038,6.552893,7.38063,7.548872,...,9.171319,9.078431,9.045312,9.398147,9.363662,8.89812,9.157393,9.386225,8.934824,8.95245
Conditions,Not Reported,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Solid Tissue Normal,Primary Tumor,Primary Tumor,Primary Tumor,...,Not Reported,Primary Tumor,Ovarian Tumor Sample,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Solid Tissue Normal,Solid Tissue Normal

In [74]:
export_df_normalized

,01CPTAC_1,01CPTAC_2,01CPTAC_3,01CPTAC_4,01CPTAC_5,01CPTAC_6,01CPTAC_7,01CPTAC_8,01CPTAC_9,01CPTAC_10,...,13CPTAC_1,13CPTAC_2,13CPTAC_3,13CPTAC_4,13CPTAC_5,13CPTAC_6,13CPTAC_7,13CPTAC_8,13CPTAC_9,13CPTAC_10
0,0.935603,-0.086369,0.786048,1.069258,0.860449,-0.130177,-0.311762,0.131637,0.537098,1.431399,...,0.632951,1.099141,1.107433,0.974463,1.019426,1.630872,1.682706,0.816556,0.104716,-0.496306
1,1.551572,-0.197678,0.370067,-0.161171,0.359997,-0.262972,-0.413216,0.394467,-0.055829,0.447476,...,1.002573,-0.051359,0.999509,-0.185467,-0.015808,0.012965,-0.818991,-0.60685,-0.62555,0.192115
2,-0.473628,-2.233779,-1.483126,-0.341969,-0.6778,-1.742391,-2.344356,-1.39933,-0.273224,-0.258776,...,1.126813,1.173089,1.45008,0.16036,1.093243,1.152555,0.800632,0.648046,-0.505979,-0.479573
3,0.668724,0.438768,0.518318,0.46211,0.445675,0.481358,0.208015,0.381343,0.464918,0.480309,...,0.736181,0.532446,0.898038,0.501932,0.689904,0.679189,0.620348,0.570685,0.405587,0.540742
4,-1.199512,-2.270995,-2.151234,-1.813642,-2.031302,-1.815763,-1.708907,-2.092016,-2.260684,-1.897957,...,1.491828,0.755135,1.422832,1.76043,1.342536,0.76432,0.765718,1.032165,1.650714,1.483676
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10560,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,...,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322,-0.285322
10561,1.244693,-0.185421,-0.188071,-0.432699,-0.548928,-0.763505,-1.000697,-0.198328,-1.138348,-0.339839,...,0.684224,-1.094001,1.169143,1.090344,0.199661,-1.000407,-1.437192,-0.500733,-0.907436,-0.554253
10562,0.264142,0.152504,0.218174,0.163965,0.209363,0.241004,0.071909,0.233074,0.258264,0.286151,...,0.588388,0.33144,0.380212,0.500248,0.336827,0.377802,0.259716,0.294635,0.181953,0.187042
10563,-0.476325,-1.209986,-0.257583,-0.64556,-0.496014,-1.183254,-0.942629,-1.069061,-0.42759,-0.297207,...,0.960141,0.888155,0.86249,1.135926,1.109201,0.74842,0.949349,1.126686,0.776864,0.790524
Conditions,Not Reported,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Solid Tissue Normal,Primary Tumor,Primary Tumor,Primary Tumor,...,Not Reported,Primary Tumor,Ovarian Tumor Sample,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Primary Tumor,Solid Tissue Normal,Solid Tissue Normal